project/5_9/movies-review-site/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('update/', views.ProfileUpdate.as_view(), name='update'),
    path('password/', views.ChangePassword.as_view(), name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

project/5_9/movies-review-site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/5_9/movies-review-site/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import os


class User(AbstractUser):
    nickname = models.CharField(max_length=20, blank=False, null=False)
    followings = models.ManyToManyField('self',
                                        symmetrical=False,
                                        related_name='followers')

    def profile(instance, filename):
        return f'profiles/{instance.username}/{filename}'
    profile_image = ProcessedImageField(blank=True,
                                        upload_to=profile,
                                        processors=[ResizeToFill(300, 300)],
                                        format='JPEG',
                                        options={'quality': 80},
                                        )
    '''
    user 삭제시 프로필 이미지 삭제
    '''
    def delete(self, *args, **kargs):
        if self.profile_image:
            os.remove(os.path.join(
                settings.MEDIA_ROOT, self.profile_image.path))
        super(User, self).delete(*args, **kargs)
    '''
    user 프로필 이미지 변경시 과거 이미지 삭제
    '''
    def save(self, *args, **kwargs):
        if self.id:
            old_user = User.objects.get(id=self.id)
            if self.profile_image != old_user.profile_image:
                if old_user.profile_image:
                    os.remove(os.path.join(settings.MEDIA_ROOT,
                              old_user.profile_image.path))
        super(User, self).save(*args, **kwargs)

    birthday = models.DateField(null=True, blank=True)
    color = models.CharField(max_length=100, blank=True, null=True)

project/5_9/movies-review-site/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms
# allauth
from allauth.socialaccount.forms import SignupForm

#회원가입
class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '아이디'
            }
        ),
    )
    nickname = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '닉네임'
            }
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '이메일'
            }
        ),
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '비밀번호'
            }
        ),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '비밀번호 확인'
            }
        ),
    )
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'nickname', 'password1', 'password2',)

#회원정보 수정
class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일',
            }
        ),
        required=False,
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름',
            }
        ),
        required=False,
    )
    nickname = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '닉네임',
            }
        ),
        required=False,
    )
    profile_image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            }
        ),
        required=False
    )
    birthday = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
            }
        ),
        required=False
    )
    color = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'color-picker',
            }
        ),
        required=False,    
    )
# 기본 프로필 색상 설정 & 변경시 출력
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'instance' in kwargs:
            instance = kwargs['instance']
            self.fields['color'].widget.attrs['value'] = instance.color or '#ffbfd3;'
        else:
            self.fields['color'].widget.attrs['value'] = '#ffbfd3;'


    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'last_name', 'birthday', 'profile_image', 'nickname', 'color')

# 비밀번호 수정
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '기존 비밀번호',
            }
        )
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '새 비밀번호',
            }
        )
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호 확인',
            }
        )
    )
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     self.fields['old_password'].widget.attrs['placeholder'] = '현재 비밀번호를 입력해 주세요'
    #     self.fields['new_password1'].widget.attrs['placeholder'] = '새 비밀번호를 입력해 주세요'
    #     self.fields['new_password2'].widget.attrs['placeholder'] = '새 비밀번호를 다시 입력해 주세요'

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '아이디',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control account-field',
                'placeholder': '비밀번호',
            }
        )
    )


class CustomSocialSignupForm(SignupForm):
    email = forms.EmailField(label='구글 이메일', widget=forms.EmailInput(attrs={
                'class': 'form-control account-field',
                'placeholder': '이메일'
            }), required=False)
    nickname = forms.CharField(required=True, widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '닉네임',
            }
        ),  max_length=20, label='닉네임')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nickname'].widget.attrs.update({'autofocus': True})
        # username 숨기고 / 구글에서 받아오는 정보중 sub값 넣음 (의미없는)
        self.fields['username'].widget = forms.HiddenInput()
        self.initial['username'] = self.sociallogin.account.extra_data.get('sub')

    def save(self, request):
        user = super().save(request)
        # 구글 username으로 저장
        user.nickname = self.cleaned_data.get('nickname')
        user.save()
        return user

project/5_9/movies-review-site/accounts/views.py
import os
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View 
from django.shortcuts import render, redirect
from dotenv import load_dotenv
import requests
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from reviews.models import Review
from movies.models import Collection, MovieLike
from reviews.models import Emote, Review
from movies.models import Collection

load_dotenv()
base_url = 'https://api.themoviedb.org/3'
api_key = os.getenv('TMDB_API_KEY')


class Signup(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})
    
    def post(self, request):
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('movies:index')

        # 양식에 어긋났을때
        form = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'form': form})


class Login(View):
    def get(self, request):
        form = CustomAuthenticationForm()
        context = {
        'form': form,
        }
        return render(request, 'accounts/login.html', context) # <-- 나중에 바꾸기
    
    def post(self, request):
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
        context = {
        'form': form,
        }
        return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')


# 유저 정보 외에 다른 영화나 리뷰 정보들은 추후에 작업
# 지금은 유저만 넘김
def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    collections = Collection.objects.filter(user=person).prefetch_related('moviecollection_set').order_by('-pk')
    reviews = Review.objects.filter(user_id=person.id).order_by('-pk')
    review_info_lst = []
    for review in reviews:
        review_like = Emote.objects.filter(review=review.pk, emotion=1)
        review_dislike = Emote.objects.filter(review=review.pk, emotion=0)
        liked_by_user = False
        for emote in review_like:
            if request.user == emote.user:
                liked_by_user = True
                break
        disliked_by_user = False
        for emote in review_dislike:
            if request.user == emote.user:
                disliked_by_user = True
                break
        review_info_lst.append((review, liked_by_user, disliked_by_user))
        
    like_movies = MovieLike.objects.filter(user=person).order_by('-pk')
    like_movies_info = []
    params = {
        'api_key': api_key,
        'language': 'ko-KR',
    }
    for movie in like_movies:
        path = f'/movie/{movie.movie_id}'
        movie = requests.get(base_url+path, params=params).json()
        like_movies_info.append(movie)
    
    context = {
        'reviews': reviews,
        'person': person,
        'collections': collections,
        'like_movies': like_movies_info,
        'review_info_lst': review_info_lst,
    }
    return render(request, 'accounts/profile.html', context)


class ProfileUpdate(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        form = CustomUserChangeForm(instance=request.user)
        return render(request, 'accounts/update.html', {'form': form})

    def post(self, request):
        print('post pass')
        form = CustomUserChangeForm(request.POST, instance=request.user, files=request.FILES)

        if form.is_valid():
            print('form valid pass')
            form.save()
            return redirect('accounts:profile', request.user)
        
        context = {
        'form': form,
        }
        return render(request, 'accounts/update.html', {'form': form})


class ChangePassword(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):
        form = CustomPasswordChangeForm(request.user)
        return render(request, 'accounts/change_password.html', {'form': form})
    
    def post(self, request):
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # 로그인 유지
            update_session_auth_hash(request, user)
            return redirect('movies:profile')


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user
    if you != me:
        if you.followers.filter(pk=request.user.pk).exists():
            you.followers.remove(me)
            is_followed = False
        else:
            you.followers.add(me)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': you.followings.count(),
            'followers_count': you.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', you.user_pk)

project/5_9/movies-review-site/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <div class="account-update-form mx-auto">
      <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
          <a class="nav-link account-text-color" href="{% url 'accounts:update' %}">회원정보 변경</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">비밀번호 변경</a>
        </li>
      </ul>
      
      <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="input-group mb-3">
            {{ field }}
            {% if field.errors %}
              <span class="text-white">{{ field.errors }}</span>
            {% endif %}
          </div>
        {% endfor %}
        <div class="d-flex">
          <a class="btn btn-secondary w-50 me-3" href="{% url 'accounts:profile' request.user.username %}">취소</a>
          <button class="btn btn-primary w-50 btn-pink" type="submit">비밀번호 변경</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

project/5_9/movies-review-site/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load socialaccount %}
{% load static %}

{% block content %}
<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <form class="account-login-form mx-auto" action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="input-group mb-3">
          {{ field }}
          {% if field.errors %}
            <span class="text-white">{{ field.errors }}</span>
          {% endif %}
        </div>
      {% endfor %}
      <div class="d-grid">
        <button class="btn btn-primary btn-pink" type="submit">로그인</button>
      </div>
    </form>
    <div class="account-info mx-auto text-center">
      <div class="mt-3">
        <a class="a-underline" href="#">비밀번호를 잊어버리셨나요?</a>
        <p class="account-text-color mt-3">계정이 없으신가요? <a class="a-underline" href="{% url 'accounts:signup' %}">회원가입</a></p>
      </div>
      <div class="pt-3">
        <a href="{% provider_login_url 'google' %}"><img src="{% static 'img/btn_google_signin_light_normal_web.png' %}"></a>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

project/5_9/movies-review-site/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load socialaccount %}
{% load static %}

{% block content %}
<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <form class="account-signup-form mx-auto" action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="input-group mb-3">
          {{ field }}
          {% if field.errors %}
            <span class="text-white">{{ field.errors }}</span>
          {% endif %}
        </div>
      {% endfor %}
      <div class="d-grid">
        <button class="btn btn-primary btn-pink" type="submit">회원가입</button>
      </div>
    </form>
    <div class="account-info mx-auto text-center">
      <p class="account-text-color mt-3">이미 가입하셨나요? <a class='a-underline' href="{% url 'accounts:login' %}">로그인</a></p>
      <div class="pt-3">
        <a href="{% provider_login_url 'google' %}"><img src="{% static 'img/btn_google_signin_light_normal_web.png' %}"></a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

project/5_9/movies-review-site/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.css">


<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <div class="account-update-form mx-auto">
      <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">회원정보 변경</a>
        </li>
        <li class="nav-item">
          <a class="nav-link account-text-color" href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
        </li>
      </ul>
      
      <form class="" action="{% url 'accounts:update' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          <div class="input-group mb-3">
            {% if field.name == 'color' %}
              <p class="color-text">프로필 색상 변경</p>
              <p>{{ field }}</p>
            {% else %}
              {{ field }}
              {% if field.errors %}
                <span class="text-white">{{ field.errors }}</span>
              {% endif %}
            {% endif %}
          </div>
        {% endfor %}
        <div class="d-flex gap-3">
          <a class="btn btn-secondary flex-grow-1" href="{% url 'accounts:profile' request.user.username %}">취소</a>
          <button class="btn btn-primary flex-grow-1 btn-pink" type="submit">수정</button>
        </div>
      </form>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.js"></script>
<script src="{% static 'js/accounts/color.js' %}"></script>
{% endblock content %}