project/5_9/movies-review-site/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('update/', views.ProfileUpdate.as_view(), name='update'),
    path('password/', views.ChangePassword.as_view(), name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

project/5_9/movies-review-site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('movies/', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/5_9/movies-review-site/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),
    path('person/<int:person_id>/', views.person_detail, name='person_detail'),
    path('search/', views.search, name='search'),
    path('like/<int:movie_id>/', views.like, name='like'),
    path('collection/create/<str:username>/', views.create, name='create'),
    path('collection/<str:username>/<int:collection_pk>/', views.collection_detail, name='collection_detail'),
    path('collection/update/<str:username>/<int:collection_pk>/', views.update, name='update'),
    path('collection/delete/<str:username>/<int:collection_pk>/', views.delete, name='delete'),
    path('collections/<int:collection_pk>/like/', views.like_collection, name='like_collection'),
    path('collections/add/<int:collection_pk>/<int:movie_id>/', views.add_collection_movie, name='add_collection_movie'),
    path('api/key/', views.api_convert, name='api_convert'),
    # 장르별 영화조회
    path('genre/<str:genre_name>/', views.genre_movies, name='genre_movies'),
]

project/5_9/movies-review-site/movies/models.py
from django.db import models
from django.conf import settings
from dotenv import load_dotenv
import os
import requests
load_dotenv()


class MovieLike(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie_id = models.IntegerField()


class Collection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_collections')
    title = models.CharField(max_length=100)
    content = models.TextField()


class MovieCollection(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    movie_id = models.IntegerField()
    movie_poster = models.CharField(max_length=200, default='', null=True)

    def __str__(self):
        url = f'https://api.themoviedb.org/3/movie/{self.movie_id}'
        api_key = os.getenv('TMDB_API_KEY')
        params = {
            'api_key': api_key,
            'language': 'ko-KR',
        }
        movie = requests.get(url, params=params).json()
        return movie['title']

project/5_9/movies-review-site/movies/forms.py
from django import forms
from .models import Collection, MovieCollection


class CollectionForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'collection-field',
                'placeholder': '컬렉션 제목',
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'collection-field',
                'placeholder': '설명 입력하기',
            }
        )
    )
    class Meta:
        model = Collection
        fields = ('title', 'content',)


class CollectionMovieDeleteForm(forms.ModelForm):
    delete_movies = forms.ModelMultipleChoiceField(
        # label = '삭제할 영화 선택',
        queryset=MovieCollection.objects.all(),
        widget=forms.CheckboxSelectMultiple(
            attrs={
                'class': 'text-dark',
            }
        ),
        required=False,
    )
    class Meta:
        model = MovieCollection
        fields = []

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)
        if instance:
            self.fields['delete_movies'].queryset = instance.moviecollection_set.all()
    
    def save(self, commit=True):
        for movie in self.cleaned_data['delete_movies']:
            movie.delete()

project/5_9/movies-review-site/movies/views.py
import re
from django.shortcuts import render, redirect, get_object_or_404
from .models import MovieLike, Collection, MovieCollection
from reviews.models import Review, Emote
from .forms import CollectionForm, CollectionMovieDeleteForm
from reviews.models import Review
from reviews.forms import ReviewForm
from dotenv import load_dotenv
from django.utils import timezone
import os
import requests
import pycountry
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.db.models import Avg, Count
from django.http import JsonResponse
from django.core.paginator import Paginator
import json
from django.db.models import Avg, Count, Q

# 번역 테스트
from googletrans  import Translator


load_dotenv()
base_url = 'https://api.themoviedb.org/3'
api_key = os.getenv('TMDB_API_KEY')


def get_average_rating(movies):
    movie_ids = [movie['id'] for movie in movies]
    review_counts = Review.objects.filter(movie__in=movie_ids).values('movie').annotate(count=Count('id'))

    rating_sums = {}
    rating_counts = {}

    for review_count in review_counts:
        movie_id = review_count['movie']
        count = review_count['count']
        rating_sums[movie_id] = 0
        rating_counts[movie_id] = count

    if review_counts:
        reviews = Review.objects.filter(movie__in=movie_ids).values('movie').annotate(avg_rating=Avg('rating'))
        for review in reviews:
            movie_id = review['movie']
            avg_rating = review['avg_rating']
            rating_sums[movie_id] = avg_rating * rating_counts[movie_id]

    for movie in movies:
        movie_id = movie['id']
        avg_rating = rating_sums.get(movie_id, 0) / rating_counts.get(movie_id, 1)
        movie['avg_rating'] = round(avg_rating, 1) if rating_counts.get(movie_id, 0) > 0 else ''


def index(request):
    # 현재 시간
    now_time = timezone.now()

    params = {
        'api_key' : api_key,
        'language': 'ko-kr',
        'region'  : 'kr',
    }

    # 현재 상영 영화 인기순으로 5개
    path = '/movie/now_playing'
    playing_movies_response = requests.get(base_url+path, params=params).json()
    playing_movies = sorted(playing_movies_response['results'], key=lambda x: x['popularity'], reverse=True)[:15]
    get_average_rating(playing_movies)
    
    playing_movies_trailers = []
    for movie in playing_movies:
        movie_id = movie['id']
        path = f'/movie/{movie_id}/videos'
        params_trailer = {
            'api_key': api_key,
            'movie_id': movie_id,
        }
        videos = requests.get(base_url+path, params=params_trailer).json()['results']
        for video in videos:
            if video['type'] == 'Trailer':
                video_key = video['key']
                playing_movies_trailers.append(video_key)
                break


    # 인기영화 5개
    path = '/movie/popular'
    popular_movies_response = requests.get(base_url+path, params=params).json()
    popular_movies = popular_movies_response['results'][:15]
    get_average_rating(popular_movies)

    # 평점 높은 영화
    path = '/movie/top_rated'
    top_movies_response = requests.get(base_url+path, params=params).json()
    top_movies = top_movies_response['results'][:15]
    get_average_rating(top_movies)

    # 상영예정작(인기 많은 5개 뽑아서 d-day순으로 정렬)
    path = '/movie/upcoming'
    upcoming_movies_response = requests.get(base_url+path, params=params).json()
    upcoming_movies = sorted(upcoming_movies_response['results'], key=lambda x: x['popularity'], reverse=True)[:15]
    get_average_rating(upcoming_movies)

    # 컬렉션 인기순
    collections = Collection.objects.prefetch_related('moviecollection_set').annotate(likes_cnt=Count('like_users')).all().order_by('-likes_cnt', '-pk')
    collections = collections[:10] if len(collections) > 10 else collections

    context = {
        'playing_movies_trailers': playing_movies_trailers,
        'now_time': now_time,
        'playing_movies': playing_movies,
        'popular_movies': popular_movies,
        'top_movies': top_movies,
        'upcoming_movies': sorted(upcoming_movies, key=lambda x: x['release_date']),
        'collections': collections,
    }
    
    return render(request, 'movies/index.html', context)


def detail(request, movie_id):
    # 리뷰 폼
    review_form = ReviewForm()
    
    # 리뷰
    reviews = Review.objects.filter(movie=movie_id).order_by('-pk')
    total_reviews = len(reviews)

    review_info_lst = []

    for review in reviews:
        review_like = Emote.objects.filter(review=review.pk, emotion=1)
        review_dislike = Emote.objects.filter(review=review.pk, emotion=0)
        liked_by_user = False
        for emote in review_like:
            if request.user == emote.user:
                liked_by_user = True
                break
        disliked_by_user = False
        for emote in review_dislike:
            if request.user == emote.user:
                disliked_by_user = True
                break
        review_info_lst.append((review, liked_by_user, disliked_by_user))
    
    # 평점 계산
    rating_dict = {0.0: 0, 0.5: 0, 1.0: 0, 1.5: 0, 2.0: 0, 2.5: 0, 3.0: 0, 3.5: 0, 4.0: 0, 4.5: 0, 5.0: 0}
    for review in reviews:
        rating_dict[review.rating] += 1
    ratings = list(rating_dict.values())
    
    sum_ratings = 0
    avg_rating = 0
    for key, value in rating_dict.items():
        sum_ratings += key * value
    if total_reviews:
        avg_rating = round((sum_ratings / total_reviews), 1)
    
    avg_rating_percent = avg_rating * 0.2 * 100

    # 출연/제작
    path = f'/movie/{movie_id}'
    params = {
        'api_key': api_key,
        'language': 'ko-KR',
    }
    movie = requests.get(base_url+path, params=params).json()
    movie_credits = requests.get(base_url+path+'/credits', params=params).json()

    # 메인 예고편
    movie_id = movie['id']
    path = f'/movie/{movie_id}/videos'
    params = {
        'api_key': api_key,
        'movie_id': movie_id,
    }
    videos = requests.get(base_url+path, params=params).json()['results']
    video_key = ''
    for video in videos:
        if video['type'] == 'Trailer':
            video_key = video['key']
            break

    # 비슷한 작품
    movie_id = movie['id']
    path = f'/movie/{movie_id}/recommendations'
    params = {
        'api_key': api_key,
        'movie_id': movie_id,
        'language': 'ko-kr',
    }
    recommend = requests.get(base_url+path, params=params).json()['results'][:10]

    # 개봉연도
    year = movie['release_date'][:4]
    
    # 장르 불러오기
    genres_list = movie['genres']
    tmp = []
    for genre in genres_list:
        tmp.append(genre['name'])
    genres = '/'.join(tmp)
    
    # 국가 코드
    if movie['production_countries']:
        country_code = movie['production_countries'][0]['iso_3166_1']
        try:
            country = pycountry.countries.get(alpha_2=country_code).name
        except AttributeError:
            pass
    else:
        country = ''

    # 감독
    crews = []
    for crew in movie_credits['crew']:
        if crew['job'] == 'Director':
            crews.append(crew)
    for crew in crews:
        crews_tmp = []
        person_id = crew['id']
        path = f'/person/{person_id}'
        params = {
            'api_key': api_key,
            'language': 'ko-KR',
        }
        person = requests.get(base_url+path, params=params).json()
        name = check_korean_name(person, crews_tmp)
        crew['kor_name'] = name

    # 출연진
    casts = movie_credits['cast']
    if len(casts) > 12 - len(crews):
        casts = casts[:12-len(crews)]
    
    for cast in casts:
        casts_tmp = []
        person_id = cast['id']
        path = f'/person/{person_id}'
        params = {
            'api_key': api_key,
            'language': 'ko-KR',
        }
        person = requests.get(base_url+path, params=params).json()
        name = check_korean_name(person, casts_tmp)
        cast['kor_name'] = name
    
    # 영화 보고싶어요 눌렀는지
    # 로그인 유저인가?
    if request.user.is_authenticated:
        if MovieLike.objects.filter(user=request.user, movie_id=movie['id']).exists():
            is_like_movie = True
        else:
            is_like_movie = False
    else:
        is_like_movie = False
    
    # 해당 영화가 담긴 컬렉션
    movie_collections = MovieCollection.objects.filter(movie_id=movie_id).select_related('collection').annotate(like_number=Count('collection__like_users')).order_by('-like_number', '-pk')

    # 이 영화가 내 컬렉션에 있는지
    if request.user.is_authenticated:
        my_collection = Collection.objects.filter(user=request.user).annotate(
            movie_cnt=Count('moviecollection', filter=Q(moviecollection__movie_id=movie_id))
        )
    else:
        my_collection = False

    # # 키워드 테스트
    # path = f'/movie/{movie_id}/keywords'
    # params = {
    #     'api_key': api_key,
    # }
    # test = requests.get(base_url+path, params=params).json()['keywords']
    # translator = Translator()
    # keywords = [i['name'] for i in test[:4]]
    # kr_keywords = []
    # for keyword in keywords:
    #     translation = translator.translate(keyword, src='en', dest='ko')
    #     if translation.text == '계속':
    #         translation.text = '시퀄'
    #     kr_keywords.append(translation.text)
        
    # test_response = requests.get(base_url+path, params=params).json()
    # test = test_response.get('keywords', [])
    # translator = Translator()
    # n = 1
    # keywords = []
    # for dict in test:
    #     keywords.append(dict['name'])
    #     n += 1
    #     if n == 5:
    #         break

    # kr_keywords = []
    
    # for keyword in keywords:
    #     translation = translator.translate(keyword, src='en', dest='ko')
    #     if translation.text == '계속':
    #         translation.text = '시퀄'
    #     kr_keywords.append(translation.text)
    # print(kr_keywords)

    context = {
        'avg_rating_percent': avg_rating_percent,
        'total_reviews': total_reviews,
        'avg_rating': avg_rating,
        'ratings': ratings,

project/5_9/movies-review-site/movies/templates/movies/collection_detail.html
{% extends 'base.html' %}

{% load static %}
{% load mathfilters %}

{% block content %}
<!-- 배경 -->
<div class="collcetion-bg-carousel">
  <div class="d-flex collection-banner">
    {% for movie in movies|slice:'7' %}
      <img class="bg-collection-poster-size stack-{{forloop.counter}}"src="https://image.tmdb.org/t/p/w1280{{ movie.poster_path }}" alt="">
    {% endfor %}
  </div>
</div>
<!-- 프로필 -->
<div class="bg-black pb-3">
  <div class="container">
    <div class="container-py d-flex justify-content-between align-items-center pt-3">
      <a href="{% url 'accounts:profile' person.username %}">
        <div class="d-flex align-items-center gap-3">
          {% if person.profile_image %}
            <img class="collection-profile-img rounded-circle" src="{{ person.profile_image.url }}" alt="profile image">
          {% else %}
            <img class="collection-profile-img" src="{% static 'img/profile-img.png' %}" alt="no image">
          {% endif %}
          <p class="fs-6 text-white">{{ person.nickname }}</p>
        </div>
      </a>
      {% if request.user == person %}
      <div class="d-flex align-itmes-center gap-3">
        <a class="my-btn" href="{% url 'movies:update' person.username collection.pk %}">수정하기</a>
        <form action="{% url 'movies:delete' person.username collection.pk %}" method="POST">
          {% csrf_token %}
          <button class="my-btn border-0" type="submit">삭제</button>
        </form>
      </div>
      {% endif %}
    </div>
  </div>
</div>
<section class="detail-bg-color">
  <div class="container c-wrapper">
    <div class="container-py">
      <!-- 컬렉션 -->
      <div class="c-detail">
        <h3 class="fs-3 mb-3">{{ collection.title }}</h3>
        <p class="fs-6 text-secondary mb-5">{{ collection.content }}</p>
        
        <form class="like-forms" data-collection-id="{{ collection.pk }}">
          {% csrf_token %}
          {% if request.user in collection.like_users.all %}
            <button class="ps-0 border-0 bg-transparent collection-like" type="submit"><i id="like-{{ collection.pk }}" class="bi bi-suit-heart-fill"></i></button>
          {% else %}
            <button class="ps-0 border-0 bg-transparent collection-like" type="submit"><i id="like-{{ collection.pk }}" class="bi bi-suit-heart"></i></button>
          {% endif %}
          <span id="like_users_count">{{ like_users_count }}</span>
        </form>
        
        <hr>
        <div class='mb-3 d-flex align-items-center gap-2'>
          <span class="c-main-title">작품들</span>
          <span class="collection-movie-count">{{ movies|length }}</span>
        </div>

        <div class="row row-cols-2 row-cols-md-5 g-1">
          {% for movie in movies %}
          <a class="black-font mb-3" href="{% url 'movies:detail' movie.id %}">
            <div class="movie-card">
              <div class="collection-poster-wrapper">
                {% if movie.poster_path %}
                <img class="collection-movie-poster" src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="">
                {% else %}
                <img class="collection-movie-poster" src="{% static 'img/no-poster-2.png' %}" alt="">
                {% endif %}
              </div>
            </div>
            <p class="black-movie-title">{{ movie.title }}</p>
            <p class="black-movie-content">{{ movie.release_date }}</p>
            <p class="black-movie-avg">평균<img class="star-size" src="{% static 'img/rating-star.svg' %}" alt="">{{ movie.vote_average|mul:0.5|floatformat:1 }}</p>
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const forms = document.querySelectorAll('.like-forms');
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

  forms.forEach((form) => {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      const collectionId = event.target.dataset.collectionId;
      
      
      axios({
        method: "POST",
        url: `/movies/collections/${collectionId}/like/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then((response) => {
          const likeIcon = document.querySelector(`#like-${collectionId}`);
          const likeCount = document.querySelector(`#like_users_count`)
          const isLiked = response.data.is_liked;
          
          if (isLiked === true) {
            likeIcon.classList.remove('bi', 'bi-suit-heart');
            likeIcon.classList.add('bi', 'bi-suit-heart-fill');
            
          } else {
            likeIcon.classList.remove('bi-suit-heart-fill');
            likeIcon.classList.add('bi', 'bi-suit-heart');
            
          }
          likeCount.innerText = response.data.like_users_count;
        })
        .catch((error) => {
          console.log(error.response);
        });
    });
  });
</script>



{% endblock content %}

project/5_9/movies-review-site/movies/templates/movies/create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <div class="container container-pt white-font">
      <div class="mt-5 collcetion mx-auto">
        <form action="{% url 'movies:create' request.user.username %}" method="POST">
          <div class="d-flex justify-content-between align-items-center mb-4">
            <a class="fs-5 text-dark" href="{% url 'accounts:profile' request.user.username %}">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </a>
            <button class="my-btn">
              저장
            </button>
          </div>
          {% csrf_token %}
          {% for field in collection_form %}
            <div class="input-group mb-3">
              {{ field }}
            </div>
          {% endfor %}

          <!-- 추가할 영화 리스트 출력될 부분 -->
          <div id="selected-list" class="d-flex gap-3 flex-wrap">
            <button type="button" class="btn btn-secondary movie-poster-size fs-1 opacity-50" data-bs-toggle="modal" data-bs-target="#addList">
              +
            </button>
          </div>
          <input type="hidden" id="movies-input" name="selected_list">
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="addList" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header border-top border-bottom">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="d-flex align-items-center border-bottom ps-3">
        <i class="bi bi-search"></i>
        <input class="px-1 py-2 bg-transparent border-0 search collcetion-search" type="text" id="search-input" data-user-name="{{ request.user.username }}" placeholder="작품 검색" aria-label="Search">
      </div>
      <button class="" type="submit" hidden>Search</button>
      <div class="modal-body" id="search-results">
        
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/movies/create_collection.js' %}"></script>
{% endblock content %}

project/5_9/movies-review-site/movies/templates/movies/search.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load mathfilters %}

{% block content %}
<!--배경-->
<div class="page-bg-wrapper">
  <div class="page-bg-inner">
    <div class="container container-pt white-font">
      <!--결과-->
      <p class="title-size result-title">'{{ key_word }}' 검색 결과</p>
      <p class="title-size result-text">{{ count_results|intcomma }} 건의 결과가 있습니다.</p>
      
<!--영화 START-->

    <!-- 영화일경우-->
    <div>
      <p class="title-size result-text">영화</p>
      <div class="search-card-wrap">
          {% if movies %}
            {% for movie in movies %}
                    <a class="search-card" href="{% url 'movies:detail' movie.id %}">
                      {% if movie.poster_path %}
                        <img class="poster-size" src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ result.title }}">
                      {% else %}
                        <img class="poster-size" src="{% static 'img/no-poster-2.png' %}" alt="">
                      {% endif %}
                        <p class="white-movie-title">{{ movie.title }}</p>
                        <p class="white-movie-content">{{ movie.release_date|slice:":4" }}</p>
                        <p class="white-movie-avg">평점<img class="star-size" src="{% static 'img/rating-star.svg' %}" alt="">{{ movie.vote_average|mul:0.5|floatformat:1 }}</p>
                    </a>
            {% endfor %}
          {% elif not movies %}
            <p class="result-text-none">검색 결과가 없습니다.</p>
          {% endif %}
      </div>
    </div>
    

    

<!--영화 END-->

<!--인물 START-->

    <!-- 인물일경우 -->
    <div>
      <p class="title-size result-text">인물</p>
      <div class="search-card-wrap">
          {% if people %}
            {% for person in people %}
                    <a class="search-card"href="{% url 'movies:person_detail' person.id %}">
                        {% if person.profile_path %}
                          <img class="poster-size" src="https://image.tmdb.org/t/p/w500{{ person.profile_path }}" alt="{{ person.name }}">
                        {% else %}
                          <img class="poster-size" src="{% static 'img/no-poster-2.png' %}" alt="">
                        {% endif %}
                        <p class="white-movie-title">{{ person.name }}</p>
                        <p class="white-movie-content">대표작: {{ person.known_for.0.title }}</p>
                    </a>
            {% endfor %}
          {% elif not people %}
            <p class="result-text-none">검색 결과가 없습니다.</p>
          {% endif %}
      </div>
    </div>
    
<!--인물 END-->

    <!-- 페이지 -->
    <div class="pagination justify-content-center">
      <ul class="pagination my-5">
        {% if pages.has_previous %}
          <li class="page-item">
            {% if pages.previous_page_number == 1 %}
              <a class="page-link" href="?search={{ key_word }}&page={{ pages.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            {% else %}
              <a class="page-link" href="?search={{ key_word }}&page=1" aria-label="First">
                <span aria-hidden="true">&laquo;&laquo;</span>
                <span class="sr-only">First</span>
              </a>
            {% endif %}
          </li>
        {% endif %}
        
        {% for page_num in pages.paginator.page_range %}
          {% if page_num > pages.number|add:'-3' and page_num < pages.number|add:'3' %}
            <li class="page-item {% if pages.number == page_num %} active{% endif %}">
              <a class="page-link" href="?search={{ key_word }}&page={{ page_num }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}
        
        {% if pages.has_next %}
          <li class="page-item">
            {% if pages.next_page_number == pages.paginator.num_pages %}
              <a class="page-link" href="?search={{ key_word }}&page={{ pages.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            {% else %}
              <a class="page-link" href="?search={{ key_word }}&page={{ pages.paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
                <span class="sr-only">Last</span>
              </a>
            {% endif %}
          </li>
        {% endif %}
      </ul>
    </div>
    </div>
  </div>
</div>

{% endblock content %}