example/4-2/23.4.11 django/example/example/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/4-2/23.4.11 django/example/reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
]

example/4-2/23.4.11 django/example/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    movie = models.CharField(max_length=50)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField()
    image = models.ImageField(blank=True, upload_to='%Y/%m/%d')

example/4-2/23.4.11 django/example/reviews/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content','image',)

example/4-2/23.4.11 django/example/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment
from .forms import ReviewForm, CommentForm


def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews,
    }
    return render(request, 'reviews/index.html', context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    count = review.comment_set.count()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments,
        'count': count,
    }
    return render(request, 'reviews/detail.html', context)


def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save()
            return redirect('reviews:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
    }
    return render(request, 'reviews/create.html', context)


def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm(request.POST, request.FILES)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.save()
        return redirect('reviews:detail', review.pk)
    context = {
        'review': review,
        'comment_form': comment_form,
    }
    return render(request, 'reviews/detail.html', context)


def comment_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('reviews:detail', review_pk)

example/4-2/23.4.11 django/example/reviews/templates/reviews/create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>New</h1>
  <form action="{% url 'reviews:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <a href="{% url 'reviews:index' %}">[back]</a>
</body>
</html>

example/4-2/23.4.11 django/example/reviews/templates/reviews/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Detail</h1>
  <p>후기 번호 - {{ review.pk }}</p>
  <p>후기 제목 - {{ review.title }}</p>
  <p>후기 내용 - {{ review.content }}</p>
  <p>영화 이름 - {{ review.movie }}</p>
  <a href="{% url 'reviews:index' %}">[back]</a>
  <hr>
  <p>총 {{ count }} 개의 댓글이 있습니다.</p>
    <form action="{% url 'reviews:comment_create' review.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="댓글 생성">
  </form>
    {% for comment in comments %}
    <p>댓글 번호 - {{ comment.pk }}</p>
    <p>댓글 내용 - {{ comment.content }}</p>
    {% if comment.image %}
    <p>댓글 이미지 - <img src="{{ comment.image.url }}" alt="IMAGE"></p>
    {% endif %}
    <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="댓글 삭제">
   </form>
    {% endfor %}

</body>
</html>

example/4-2/23.4.11 django/example/reviews/templates/reviews/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <a href="{% url 'reviews:create' %}">[CREATE]</a>
  {% for review in reviews %}
  <p>제목: 
    <a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
  </p>
  <p>내용: {{ review.content }}</p>
  <hr>
{% endfor %}
</body>
</html>