project/4_27/drunken_developer/aaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/4_27/drunken_developer/accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path('mypage/', views.mypage, name='mypage'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

project/4_27/drunken_developer/products/urls.py
from django.urls import path
from . import views


app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:product_pk>/pay_success/', views.pay_success, name='pay_success'),
    path('pay_fail/', views.pay_fail, name='pay_fail'),
    path('pay_cancel/', views.pay_cancel, name='pay_cancel'),
    path('<int:product_pk>/', views.detail, name='detail'),
    path('<int:product_pk>/delete/', views.delete, name='delete'),
    path('<int:product_pk>/update/', views.update, name='update'),
    path('<int:product_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:product_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:product_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:product_pk>/likes/', views.likes, name='likes'),
    path('<int:product_pk>/delete/', views.delete, name='delete'),
    path('<int:product_pk>/kakaopay/', views.kakaopay, name='kakaopay'),
    path('listing/', views.listing, name='listing'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiz_response/', views.quiz_response, name='quiz_response'),
    path('new_chat/', views.new_chat, name='new_chat'),
]

project/4_27/drunken_developer/products/forms.py
from django import forms
from .models import Product, Comment

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('title','content','price','discount_rate','category','alcohol_percentage','sweetness','sourness','bitterness','carbonated','volume','delivery_date','image')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['content'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['price'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['discount_rate'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['category'].widget.attrs['class'] = 'form-select mt-1'
        self.fields['alcohol_percentage'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['sweetness'].widget.attrs['class'] = 'form-select mt-1'
        self.fields['sourness'].widget.attrs['class'] = 'form-select mt-1'
        self.fields['bitterness'].widget.attrs['class'] = 'form-select mt-1'
        self.fields['carbonated'].widget.attrs['class'] = 'form-check mt-1'
        self.fields['volume'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['delivery_date'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['image'].widget.attrs['class'] = 'form-control mt-1'

class CommentForm(forms.ModelForm):
    image = forms.ImageField(
        label = False,
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            }
        ),
        required=False
    )

    class Meta:
        model = Comment
        fields = ('content','image',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['content'].widget.attrs['class'] = 'form-control mt-1'
        self.fields['content'].widget.attrs['placeholder'] = '다른 고객님에게 도움이 되도록 상품에 대한 솔직한 평가를 남겨주세요.'
        self.fields['image'].widget.attrs['class'] = 'form-control mt-1'

project/4_27/drunken_developer/products/views.py
from django.shortcuts import render,redirect
from .models import Product, Comment
from .forms import ProductForm, CommentForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Subquery, OuterRef
from django.shortcuts import get_object_or_404, get_list_or_404
from django.db.models import Q,F
from django.db.models import Count, Avg, Max
from django.db.models import Case, When, Value, IntegerField
import requests
from django.http import JsonResponse
import openai
from dotenv import load_dotenv
import os


OPEN_API_KEY = os.getenv('OPEN_API_KEY')
KAKAO_KEY = os.getenv('KAKAO_KEY')

# Create your views here.


def index(request):
    popular_products = Product.objects.annotate(num_likes=Count('like_users')).order_by('-num_likes')
    top_latest_comments = Comment.objects.all().order_by('-star','-pk')

    top_rated_products = Product.objects.annotate(num_stars=Avg('star')).order_by('-num_stars')
    discounted_products = Product.objects.annotate(
    discount_rate_max=Max('discount_rate')
    ).annotate(
    discount_price=Case(
        When(discount_rate=F('discount_rate_max'), then=F('price') - F('price') * F('discount_rate_max') / 100),
        default=F('price'),
        output_field=IntegerField(),
    )
    ).order_by('-discount_rate_max', '-discount_price')
    context = {
        'popular_products': popular_products,
        'top_latest_comments': top_latest_comments,
        'top_rated_products': top_rated_products,
        'discounted_products': discounted_products,
    }
    return render(request, 'products/index.html', context)


def detail(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    comments = product.comments.all().order_by('-pk')

    comment_comment_form = []
    for comment in comments:
        comment_form = CommentForm(instance=comment)
        comment_comment_form.append((comment, comment_form))

    sort = request.GET.get('sort','')
    if sort:
        comments = comment_sort(comments, sort)

        comment_comment_form = []
        for comment in comments:
            comment_form = CommentForm(instance=comment)
            comment_comment_form.append((comment, comment_form))

    context = {
        'product': product,
        'comment_comment_form': comment_comment_form,
    }
    return render(request, 'products/detail.html', context)

def comment_update(request, product_pk, comment_pk):
    product = Product.objects.get(pk=product_pk)
    comment = Comment.objects.get(pk=comment_pk)
    comment_form = CommentForm(request.POST,request.FILES, instance=comment)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.star = int(request.POST.get('star-rating'))
        comment.save()
        
        context = {
            'commentContent': comment.content,
            'commentImageUrl': comment.image.url,
            'commentStar_count': comment.star,
        }
        return JsonResponse(context)
    else:
        print(comment_form.errors)


def comment_sort(queryset, s):
    if s == 'recent':
        return queryset.order_by('-pk')
    elif s == 'high':
        return queryset.order_by('-star')
    else:
        return queryset.order_by('star')

@login_required
def kakaopay(request, product_pk):
    kakao_price = request.POST.get('kakao-price')
    kakao_count = request.POST.get('kakao-count')
    product = Product.objects.get(pk=product_pk)
    
    admin_key = KAKAO_KEY
    url = f'https://kapi.kakao.com/v1/payment/ready'
    headers = {
        'Authorization': f'KakaoAK {admin_key}',
    }
    data = {
        'cid': 'TC0ONETIME',
        'partner_order_id': product.pk, #주문 번호
        'partner_user_id': request.user.username, #유저 이름
        'item_name': product.title, #제품명
        'quantity': kakao_count, #수량
        'total_amount': kakao_price, #가격
        'tax_free_amount':'0',
 
        'approval_url':f'https://drinkit.kro.kr/products/{product.pk}/pay_success/', 
        'fail_url':'https://drinkit.kro.kr/products/pay_fail',
        'cancel_url':'https://drinkit.kro.kr/products/pay_cancel'
    }
    res = requests.post(url, data=data, headers=headers)
    result = res.json()
    request.session['tid'] = result['tid']
    return redirect(result['next_redirect_pc_url'])

@login_required
def pay_success(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    url = 'https://kapi.kakao.com/v1/payment/approve'
    admin_key = KAKAO_KEY
    
    headers = {
        'Authorization': f'KakaoAK {admin_key}'
    }
    data = {
        'cid':'TC0ONETIME',
        'tid': request.session['tid'], #결제 고유 번호
        'partner_order_id': product.pk, #주문 번호
        'partner_user_id': request.user.username, #유저 아이디
        'pg_token': request.GET['pg_token'] 
    }
    res = requests.post(url, data=data, headers=headers)
    result = res.json()
    context = {
        'res':res,
        'result':result,
    }
    if result.get('msg'): #msg = 오류 코드
        return redirect('products:pay_fail')
    else:
        product.purchase_users.add(request.user, through_defaults={
            'title': product.title,
            'count': result['quantity'],
            'price': result['amount']['total']
        })
        return render(request, 'products/pay_success.html', context)

@login_required
def pay_fail(request):
    return render(request, 'products/pay_fail.html')

@login_required
def pay_cancel(request):
    return render(request, 'products/pay_cancel.html')

@user_passes_test(lambda u: u.is_superuser)
def create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            fo = form.save(commit=False)
            fo.user = request.user
            fo.save()
            return redirect('products:index')
        else:
            print(form.errors)
    else:
        form = ProductForm()
    context = {
        'form': form,
    }
    return render(request, 'products/create.html', context)


@login_required
def delete(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if request.user == product.user:
        product.delete()
    return redirect('products:index')


@login_required
def update(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if request.user == product.user:
        if request.method == 'POST':
            form = ProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                form.save()
                return redirect('products:detail', product.pk)
        else:
            form = ProductForm(instance=product)
    else:
        return redirect('products:detail', product.pk)
    context = {
        'product' : product,
        'form' : form,
    }
    return render(request, 'products/update.html', context)


@login_required
def comment_create(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    comment_form = CommentForm(request.POST,request.FILES)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.product = product
        comment.user = request.user
        comment.star = int(request.POST.get('star_rating'))
        comment.save()
        return redirect('products:detail', product_pk)
    context = {
        'product': product,
        'comment_form': comment_form,
    }
    return render(request, 'products/comment_create.html', context)


@login_required
def comment_delete(request, product_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('products:detail', product_pk)

@login_required
def likes(request, product_pk):
    product = Product.objects.get(pk=product_pk)
    if product.like_users.filter(pk=request.user.pk).exists():
        product.like_users.remove(request.user)
    else:
        product.like_users.add(request.user)
    return redirect('products:detail', product_pk)

def listing(request):
    q = request.GET.get('q','')
    if q:
      q = str_kr(q)
      products = Product.objects.filter(
				Q(title__icontains=q)|
				Q(content__icontains=q)|
				Q(category__icontains=q)
			)
    else: products = Product.objects.all()

    category = request.GET.get('category','')

    alcohol_percentage = request.GET.getlist('dosu','')
    a1,a2 = 100,0
    if alcohol_percentage:
        for alcohol_per in alcohol_percentage:
            a1 = min(a1,int(alcohol_per.split(',')[0]))
            a2 = max(a2,int(alcohol_per.split(',')[1]))
    else: a1,a2 = 0,100

    sweetness = request.GET.getlist('sweet',['low','middle','strong'])
    sourness = request.GET.getlist('sourness',['low','middle','strong'])
    bitterness = request.GET.getlist('bitterness',['low','middle','strong'])
    carbonated = request.GET.getlist('carbonated',['True','False'])

    price = request.GET.get('price','')
    if price: p1,p2 = price.split(',')
    else: p1,p2 = 0,1000000

    if category:
      if category == 'all':
          products = Product.objects.all()
      else:
          products = Product.objects.filter(category = category)

    products = products.filter(
        alcohol_percentage__gte=int(a1),
        alcohol_percentage__lte=int(a2),
        sweetness__in=sweetness,
        sourness__in=sourness,
        bitterness__in=bitterness,
        carbonated__in=carbonated,
        discounted_price__gte=int(p1),
        discounted_price__lte=int(p2)
    )

    sort = request.GET.get('sort','')

    products = products.annotate(num_likes=Count('like_users')).order_by('-num_likes')

    if sort:
        products = func_sort(products, sort)

    context = {
        'products': products,
        'cate': category,
    }
    return render(request, 'products/listing.html', context)

def func_sort(queryset, s):
    if s == 'recommend':
        return queryset.annotate(num_likes=Count('like_users')).order_by('-num_likes')

project/4_27/drunken_developer/products/templates/products/comment_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}리뷰{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/comment_create.css' %}">

<div class='comment-create-body'>
  <div class='container w-50'>

    <form action="{% url 'products:comment_create' product.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class='review-header'>
        <div class='d-flex'>
          <div class='review-header-img'>
            <img class='w-100' src="{% static 'image/review.png' %}" alt="review">
          </div>
          <h4>상품 리뷰</h4>
        </div>
  
        <p>이 상품의 품질에 대해서 얼마나 만족하시나요?</p>
      </div>


      <hr class='hr'>

      <div class='d-flex my-3'>
        {% if product.image %}
          <div class='comment-create-img'>
            <img class='h-100' src="{{ product.image.url }}" alt="{{ product.title }}">
          </div>
        {% endif %}

        <div>
          <div class='comment-product-title'>
            {{ product.title }}
          </div>

          <div class='d-flex'>
            <button type="button" class='comment_star' id="star1" data-value="1">
              <img src="{% static 'image/star1.svg' %}" id="img1" alt="star" data-value="1">
            </button>
            <button type="button" class='comment_star' id="star2" data-value="2">
              <img src="{% static 'image/star1.svg' %}" id="img2" alt="star" data-value="2">
            </button>
            <button type="button" class='comment_star' id="star3" data-value="3">
              <img src="{% static 'image/star1.svg' %}" id="img3" alt="star" data-value="3">
            </button>
            <button type="button" class='comment_star' id="star4" data-value="4">
              <img src="{% static 'image/star1.svg' %}" id="img4" alt="star" data-value="4">
            </button>
            <button type="button" class='comment_star' id="star5" data-value="5">
              <img src="{% static 'image/star1.svg' %}" id="img5" alt="star" data-value="5">
            </button>
          </div>

          <div class='comment-star-content'>
            최고
          </div>
        </div>
      </div>

      <hr class='hr'>

      {{ comment_form.content }}

      <hr class='hr'>

      {{ comment_form.image }}

      <button id='star_rating' name='star_rating' value='5' class='btn btn-primary w-100 mt-5 mb-3' type='submit'>등록</button>
    </form>

    <div class='comment-back'>
      <a href="javascript:window.history.back();">취소</a>
    </div>

  </div>
</div>
<script src="{% static 'js/comment_create.js' %}"></script>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/create.html
{% extends 'base.html' %}
{% block title %}글 생성{% endblock title %}

{% block content %}
  <div class='container w-50'>

    <form action="{% url 'products:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button class='btn btn-primary w-100 mb-3' type='submit'>작성</button>
    </form>

  </div>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load customtags %}
{% block title %}{{ product.title }}{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">

<div class='detail-body'>

  <div class="container">
    {% comment %} 상품 메인 {% endcomment %}
    <div class='detail-mainbox'>
      {% if product.image %}
        <div class='product-img'>
          <img class='w-100' src="{{ product.image.url }}" alt="{{ product.title }}">
        </div>
      {% endif %}
  
      <div class='product-rightbox'>
        <div class='product-title'>
          {{ product.title }}
        </div>
  
        <div class='product-content'>
          {{ product.content }}
        </div>

        <div class='detail-star'>
          <div class='star-box'>
            <div class='star-gray'>
              <img src="{% static 'image/product_graystar.png' %}" alt="graystar">
            </div>
            <div class='star-star' style='width: {{ product.star_multiple }}%;'>
              <img src="{% static 'image/product_star.png' %}" alt="star">
            </div>
          </div>

          <div class='star-score'>
            {{ product.star }}
          </div>

          <div class='star-comment'>
            [{{ product.comments.count }} 리뷰]
          </div>
        </div>

        <div class='detail-content'>
          <div>종류: {{ product.category|string_kr }}</div>
          <div>도수: {{ product.alcohol_percentage }}%</div>
          <div>용량: {{ product.volume }}ml</div>
          <div class='content-delivery'>배송기간: {{ product.delivery_date }}일 이내 배송</div>
        </div>

        <div class='detail-sale'>
          판매가격:
        </div>
        
        {% if product.discount_rate %}
          <div class='detail-price'>
            {{ product.price|intcomma }}원
          </div>
        {% endif %}

        <div class='detail-discounted-price'>
          {{ product.discounted_price|intcomma }}원
        </div>

      </div>

    </div>

    {% comment %} 리모컨 {% endcomment %}
    <div class='product-sidebar'>
      <div>
        <div>옵션</div>
        <select class='form-select' name="option" id="product-option">
          <option value="option1">어떤 옵션을 원하시나요?</option>
          <option value="option2">{{ product.title }}</option>
        </select>
      </div>

      <div>
        <div>수량</div>
        <div class='sidebar-numbox'>
          <div class='sidebar-minus'>
            <button class='minus'>
              <img class='w-100' src="{% static 'image/minus.png' %}" alt="minus">
            </button>
          </div>

          <div class='sidebar-number'>
            1
          </div>

          <div class='sidebar-plus'>
            <button class='plus'>
              <img class='w-100' src="{% static 'image/plus.png' %}" alt="plus">
            </button>
          </div>
        </div>
      </div>

      <div>
        <div>총 상품가격</div>
        <div class='sidebar-price'>
          {{ product.discounted_price|intcomma }}원
        </div>
      </div>

      <form class='sidebar-interest' action="{% if user.is_anonymous %}{% url 'accounts:login' %}{% else %}{% url 'products:likes' product.pk %}{% endif %}" method="POST">
        {% csrf_token %}
        <button class='option-btn' type='submit'>
          <div class='sidebar-interest-img'>
            <img class='w-100' src="{% static 'image/interest.png' %}" alt="">
          </div>
          {% if request.user in product.like_users.all %}
            <div>관심상품 취소</div>
          {% else %}
            <div>관심상품</div>
          {% endif %}
        </button>
      </form>

      <form action="{% if user.is_anonymous %}{% url 'accounts:login' %}{% else %}{% url 'products:kakaopay' product.pk %}{% endif %}" method="POST">
        {% csrf_token %}
        <input type="hidden" class='kakao-count' name='kakao-count' value='1'>
        <input type="hidden" class='original-price' value='{{ product.discounted_price }}'>
        <button name='kakao-price' value='{{ product.discounted_price }}' type='submit' class='sidebar-buy option-btn'>
          <img class="kakao-icon" src="{% static 'image/kakao.png' %}" alt="">
          카카오페이 결제
        </button>
      </form>
    </div>

    {% comment %} 댓글 sort {% endcomment %}
    <div class='comment-create'>
      <div class='comment-create-review'>
        <a href="{% url 'products:comment_create' product.pk %}">
          <div>
            <img class='w-100' src="{% static 'image/write.svg' %}" alt="write">
          </div>
          <span>리뷰 작성하기</span>
        </a>
      </div>

      <div class='comment-create-sort'>
        <a data-bs-toggle="collapse" href="#multiCollapseExample-comment" role="button" aria-expanded="false" aria-controls="multiCollapseExample-comment">
          <div class='d-flex'>
            <div class='comment-sort-title'>최신순</div>
            <div class='comment-sort-img'>
              <img class='w-100' src="{% static 'image/down.png' %}" alt="down">
            </div>
          </div>
        </a>

        <div class="comment-collapse collapse multi-collapse" id="multiCollapseExample-comment">

          <div>
            <button value='recent' type='submit'>최신순</button>
          </div>
          <div>
            <button value='high' type='submit'>평점높은순</button>
          </div>
          <div>
            <button value='low' type='submit'>평점낮은순</button>
          </div>

        </div>
      </div>
    </div>

    {% comment %} 댓글 상세 {% endcomment %}
    <div class='detail-comment'>
      {% for comment, comment_form in comment_comment_form %}
        <div class='detail-comment-allbox'>
          <div class='comment-header'>
            <div class='comment-header-title'>
              {{ comment.user.last_name }}
            </div>

            <div class='comment-header-right'>
              <div class='star-box comment-starbox'>
                <div class='star-gray'>
                  <img class='w-100' src="{% static 'image/product_graystar.png' %}" alt="graystar">
                </div>
                <div class='star-star comment-star-star' style='width: {{ comment.star_multiple }}%;'>
                  <img src="{% static 'image/product_star.png' %}" alt="star">
                </div>
              </div>

              <div class='comment-star-count'>
                {{ comment.star }}
              </div>

              <div class='comment-time'>
                {{ comment.created_time }}
              </div>

              {% if request.user == comment.user %}
                <button class='update-btn comment-delete ms-3' type='submit'>수정</button>

                <form action="{% url 'products:comment_delete' product.pk comment.pk %}" method="POST">
                  {% csrf_token %}
                  <button class='comment-delete' class='btn btn-outline-secondary' type='submit'>삭제</button>
                </form>
              {% endif %}
            </div>
          </div>

          <div class='comment-contentbox d-block'>
            <div class='comment-content'>
              {{ comment.content|linebreaks }}
            </div>

            {% if comment.image %}
              <div class='comment-img'>
                <img class='h-100' src="{{ comment.image.url }}" alt="commentImage">
              </div>
            {% endif %}
          </div>

          <form class='comment_form mb-5 d-none' data-user-id="{{ product.pk }}" enctype="multipart/form-data">
            <input type="hidden" class="comment_pk" value="{{ comment.pk }}">

            {{ comment_form.content }}

            {% if comment.image %}
              <div class='comment_form_image'>
                <img class='w-100' src="{{ comment.image.url }}" alt="#">
              </div>
            {% endif %}

            {{ comment_form.image }}

            <div class='d-flex comment-form-star'>
              <button type="button" class='comment_star' id="star1" data-value="1">
                <img src="{% static 'image/star1.svg' %}" id="img1" alt="star" data-value="1">
              </button>
              <button type="button" class='comment_star' id="star2" data-value="2">
                <img src="{% static 'image/star1.svg' %}" id="img2" alt="star" data-value="2">
              </button>
              <button type="button" class='comment_star' id="star3" data-value="3">
                <img src="{% static 'image/star1.svg' %}" id="img3" alt="star" data-value="3">
              </button>
              <button type="button" class='comment_star' id="star4" data-value="4">
                <img src="{% static 'image/star1.svg' %}" id="img4" alt="star" data-value="4">
              </button>
              <button type="button" class='comment_star' id="star5" data-value="5">
                <img src="{% static 'image/star1.svg' %}" id="img5" alt="star" data-value="5">
              </button>

              <div class='comment-star-content'>
                최고
              </div>
            </div>

            <button id='star_rating' name='star_rating' value='{{ comment.star }}' class='comment-submit-btn' type='submit'>등록</button>
          </form>
        </div>
      {% endfor %}
    </div>

  </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/detail.js' %}"></script>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/new_chat.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class='container'>
    <form action="{% url 'products:new_chat' %}" method="POST">
      {% csrf_token %}
      <input type="text" name='q'>
      <button type='submit'>입력</button>
    </form>
  </div>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/pay_cancel.html
{% extends 'base.html' %}
{% load static %}
{% block title %}결제취소{% endblock title %}

{% block content %}
<div class='kakao-container'>
  <h3>결제가 취소되었습니다.</h3>
  <div class='kakao-main'>
    <a href="{% url 'products:index' %}">메인으로 이동</a>
  </div>
</div>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/pay_fail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}결제실패{% endblock title %}

{% block content %}
<div class='kakao-container'>
  <h3>결제에 실패하였습니다.</h3>
  <div class='kakao-main'>
    <a href="{% url 'products:index' %}">메인으로 이동</a>
  </div>
</div>
{% endblock content %}

project/4_27/drunken_developer/products/templates/products/pay_success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}결제완료{% endblock title %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/kakao.css' %}">

<div class='container'>
  <div class='complete-title'>
    결제가 완료되었습니다!
  </div>

  <div class='complete-box'>
    <div class='complete-user'>
      주문자 정보
    </div>

    <div class='complete-flex'>
      <h5>주문번호</h5>
      <p>{{ result.partner_order_id }}</p>
    </div>

    <div class='complete-flex'>
      <h5>주문자명</h5>
      <p>{{ result.partner_user_id }}</p>
    </div>

    <div class='complete-flex'>
      <h5>상품명</h5>
      <p>{{ result.item_name }}</p>
    </div>

    <div class='complete-flex'>
      <h5>구매수량</h5>
      <p>{{ result.quantity }}</p>
    </div>

    <div class='complete-flex'>
      <h5>결제금액</h5>
      <p>{{ result.amount.total }}</p>
    </div>

    <div class='complete-flex'>
      <h5>결제승인시각</h5>
      <p>{{ result.approved_at }}</p>
    </div>

    <div class='kakao-main w-100 mt-5'>
      <a href="{% url 'products:index' %}">메인으로 이동</a>
    </div>
  </div>

</div>

{% endblock content %}

project/4_27/drunken_developer/products/templates/products/update.html
{% extends 'base.html' %}

{% block content %}
<div class='container w-50'>

  <form action="{% url 'products:update' product.pk%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='btn btn-primary w-100 mb-3' type='submit'>수정</button>
  </form>

</div>
{% endblock content %}